version: '3.8'

services:
  app-dev:
    image: node:20.9
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run vue:serve
    ports:
      - 8080:8080

  app-prod:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf